services:
  - type: web
    name: sunnie-study-gpt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: YOUTUBE_ACCESS_TOKEN
        sync: false
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: VIDEO_ID
        sync: false
